### PR TITLE
Feature: Add Code service for searching in the "codes en vigueur"

### PR DESCRIPTION
**Pull request by tantale**
Hi,

This PR is a feature improvement: (it also closes #1, closes #2 and closes #3).

- Add Code service for searching in the "codes en vigueur".
- Add a service to detail code articles.
- Translate documentation in English and improve the readme.
- Change Travis CI configuration file to run build on py27, py34, py35, py36, py37.
- Use the `from __future__ import unicode_literals` directive to have Python 2 + 3 compatible RegEx (unicode raw string).
- Convert code for py27 support, using the "six" library.
- Replace the `legipy-cli.py` script by the `legipy` entry point.Fix dependencies in the project configuration: use version intervals.
- Improve the `.gitignore` file for Python, Virtualenv and PyCharm IDE.

Regards
– Laurent LAPORTE

P.S.: Travis CI seams broken.

### CODE REVIEW

**Comment by njoyard** [comment]
Nice !

It would be better IMO to split the PR into simpler pieces, most importantly to separate the following:
- python version compatibility
- translation & documentation
- cli refacto
- new features (1 PR per feature)

**Comment by RouxRC** [comment]
Sorry it took a while to merge as some other updates came into conflict. It is now merged! Many thanks, really cool features and cleaning!

**Comment by boogheta** [comment]
Hello @tantale, we're on the process of ensuring a better licensing coherence between all these related projects, so we were thinking we would move legipy from MIT to GPLv3.
Although, I don't feel comfortable doing this without your agreement considering the volume of your contributions. What do you think about it? No problem if you disagree: since Legipy is only used as a "root" dependency, leaving it as such won't be a legal issue.
Thanks in advance!

**Comment by tantale** [comment]
Hello,
I don’t mind. Have a good day.

**Comment by RouxRC** [comment]
well in the end, there was no real consensus to switch licence for some of these repo, so we'll leave it under MIT as it is, you can forget about that :)

**Pull request closed without merging**
